image: node:latest
before_script:
  - apt-get update
  - npm install
  - npm install web3
  - npm install xmlhttprequest
  - npm install -g mocha
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - mv -f ~/chromedriver /usr/local/share/
  - chmod +x /usr/local/share/chromedriver
  - ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
test:
  script:
    - mocha test/unittest/ test/selenium/