image: node:latest
before_script:
  - apt-get update
  - npm install
  - npm install web3
  - npm install xmlhttprequest
  - npm install -g mocha

test:
  script:
    - mocha test/unittest/ test/selenium/