sudo: enabled
language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"
addons: # get google-chrome-stable
  chrome: stable
before_install:
    - chmod +x ./node_modules/.bin/mocha
install:
    - npm install
    - npm install web3
    - npm install xmlhttprequest
    - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - mv -f ~/chromedriver /usr/local/share/
    - chmod +x /usr/local/share/chromedriver
    - ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
    - npm start &
    - sleep 10
    - mocha test/selenium/