sudo: enabled
language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=stable
    - BROWSER=firefox BVER=beta
    - BROWSER=firefox BVER=nightly

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=nightly
before_install:
    - chmod +x ./node_modules/.bin/mocha
install:
    - npm install
    - npm install web3
    - npm install xmlhttprequest
    - npm start &
script:
    - sleep 10
    - mocha test/selenium/