sudo: enabled
language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"

addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver

before_install:
    - chmod +x ./node_modules/.bin/mocha
install:
    - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/
    - export CHROME_BIN=chromium-browser
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - npm install
    - npm install web3
    - npm install xmlhttprequest
script:

    - sleep 10
    - npm test