sudo: enabled
language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"
addons: # get google-chrome-stable
  chrome: stable
before_install:
    - chmod +x ./node_modules/.bin/mocha
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
    - npm install
    - npm install web3
    - npm install xmlhttprequest
    - npm start &
    - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    - export DISPLAY=:99.0
script:
    - sleep 10
    - mocha test/selenium/