sudo: enabled
language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
    - chmod +x ./node_modules/.bin/mocha
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
    - npm install
    - npm install web3
    - npm install xmlhttprequest
    - npm start &
    - export DISPLAY=:99.0
script:
    - sleep 10
    - mocha test/selenium/