sudo: enabled
language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
    - chmod +x ./node_modules/.bin/mocha
install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - npm install
    - npm install web3
    - npm install xmlhttprequest
    - apt install python2.7 pip
    - pip install robotframework
    - pip install robotframework-seleniumLibrary
    - sleep 3

script:
    - npm start
    - sleep 5
    - robot test/robotframework/Connexion.robot

notifications:
  email: false
